# Generated by Django 5.1.3 on 2025-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_order_id_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_100ml',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_50ml',
            field=models.FloatField(default=0.0),
        ),
    ]
