# Generated by Django 5.1.3 on 2025-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('instapay', 'Instapay')], default='default', max_length=50),
            preserve_default=False,
        ),
    ]
