# Generated by Django 5.1.3 on 2025-02-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_100ml',
            new_name='price_30ml',
        ),
    ]
